const express = require('express')
const router = express.Router()
const {signup, login,loaduser,forgot,reset,deposit,loaddeposits,request,loaddepositlist,withdraw,edit,loadreferallist,withdrawcommision,loadhistory,getmsgs,msg,msgstatus,getrequests,loaduserwithid,approve,deletereq,cancle,getwithdraw,completew,canclew,deletew,loadwithdraw,getusers} = require("../Controllers/userController")
router.post('/signup',signup)
router.post('/login',login)
router.post('/loaduser',loaduser)
router.post('/loaduserwithid',loaduserwithid)
router.post('/forgot',forgot)
router.post('/reset',reset)
router.post('/deposit',deposit)
router.post('/withdraw',withdraw)
router.post('/request',request)
router.post('/edit',edit)
router.get('/getmsgs',getmsgs)
router.get('/getrequests',getrequests)
router.get('/getwithdraw',getwithdraw)
router.get('/getusers',getusers)
router.post('/msgstatus',msgstatus)
router.post('/msg',msg)
router.post('/approve',approve)
router.post('/loadwithdraw',loadwithdraw)
router.post('/completew',completew)
router.post('/canclew',canclew)
router.post('/approve',approve)
router.post('/deletew',deletew)
router.post('/cancle',cancle)
router.post('/withdrawcommision',withdrawcommision)
router.post('/loaddeposits',loaddeposits)
router.post('/loadhistory',loadhistory)
router.post('/loadreferallist',loadreferallist)
router.post('/loaddepositlist',loaddepositlist)



module.exports = router